#pragma once

// From glfw3.h
constexpr int LF_MOUSE_BUTTON_1 = 0;
constexpr int LF_MOUSE_BUTTON_2 = 1;
constexpr int LF_MOUSE_BUTTON_3 = 2;
constexpr int LF_MOUSE_BUTTON_4 = 3;
constexpr int LF_MOUSE_BUTTON_5 = 4;
constexpr int LF_MOUSE_BUTTON_6 = 5;
constexpr int LF_MOUSE_BUTTON_7 = 6;
constexpr int LF_MOUSE_BUTTON_8 = 7;
constexpr int LF_MOUSE_BUTTON_LAST = LF_MOUSE_BUTTON_8;
constexpr int LF_MOUSE_BUTTON_LEFT = LF_MOUSE_BUTTON_1;
constexpr int LF_MOUSE_BUTTON_RIGHT = LF_MOUSE_BUTTON_2;
constexpr int LF_MOUSE_BUTTON_MIDDLE = LF_MOUSE_BUTTON_3;

constexpr int LF_KEY_SPACE = 32;
constexpr int LF_KEY_APOSTROPHE = 39; /* ' */
constexpr int LF_KEY_COMMA = 44; /* , */
constexpr int LF_KEY_MINUS = 45; /* - */
constexpr int LF_KEY_PERIOD = 46; /* . */
constexpr int LF_KEY_SLASH = 47; /* / */
constexpr int LF_KEY_0 = 48;
constexpr int LF_KEY_1 = 49;
constexpr int LF_KEY_2 = 50;
constexpr int LF_KEY_3 = 51;
constexpr int LF_KEY_4 = 52;
constexpr int LF_KEY_5 = 53;
constexpr int LF_KEY_6 = 54;
constexpr int LF_KEY_7 = 55;
constexpr int LF_KEY_8 = 56;
constexpr int LF_KEY_9 = 57;
constexpr int LF_KEY_SEMICOLON = 59; /* ; */
constexpr int LF_KEY_EQUAL = 61; /* = */
constexpr int LF_KEY_A = 65;
constexpr int LF_KEY_B = 66;
constexpr int LF_KEY_C = 67;
constexpr int LF_KEY_D = 68;
constexpr int LF_KEY_E = 69;
constexpr int LF_KEY_F = 70;
constexpr int LF_KEY_G = 71;
constexpr int LF_KEY_H = 72;
constexpr int LF_KEY_I = 73;
constexpr int LF_KEY_J = 74;
constexpr int LF_KEY_K = 75;
constexpr int LF_KEY_L = 76;
constexpr int LF_KEY_M = 77;
constexpr int LF_KEY_N = 78;
constexpr int LF_KEY_O = 79;
constexpr int LF_KEY_P = 80;
constexpr int LF_KEY_Q = 81;
constexpr int LF_KEY_R = 82;
constexpr int LF_KEY_S = 83;
constexpr int LF_KEY_T = 84;
constexpr int LF_KEY_U = 85;
constexpr int LF_KEY_V = 86;
constexpr int LF_KEY_W = 87;
constexpr int LF_KEY_X = 88;
constexpr int LF_KEY_Y = 89;
constexpr int LF_KEY_Z = 90;
constexpr int LF_KEY_LEFT_BRACKET = 91; /* [ */
constexpr int LF_KEY_BACKSLASH = 92; /* \ */
constexpr int LF_KEY_RIGHT_BRACKET = 93; /* ] */
constexpr int LF_KEY_GRAVE_ACCENT = 96; /* ` */
constexpr int LF_KEY_WORLD_1 = 161; /* non-US #1 */
constexpr int LF_KEY_WORLD_2 = 162; /* non-US #2 */

/* Function keys */
constexpr int LF_KEY_ESCAPE = 256;
constexpr int LF_KEY_ENTER = 257;
constexpr int LF_KEY_TAB = 258;
constexpr int LF_KEY_BACKSPACE = 259;
constexpr int LF_KEY_INSERT = 260;
constexpr int LF_KEY_DELETE = 261;
constexpr int LF_KEY_RIGHT = 262;
constexpr int LF_KEY_LEFT = 263;
constexpr int LF_KEY_DOWN = 264;
constexpr int LF_KEY_UP = 265;
constexpr int LF_KEY_PAGE_UP = 266;
constexpr int LF_KEY_PAGE_DOWN = 267;
constexpr int LF_KEY_HOME = 268;
constexpr int LF_KEY_END = 269;
constexpr int LF_KEY_CAPS_LOCK = 280;
constexpr int LF_KEY_SCROLL_LOCK = 281;
constexpr int LF_KEY_NUM_LOCK = 282;
constexpr int LF_KEY_PRINT_SCREEN = 283;
constexpr int LF_KEY_PAUSE = 284;
constexpr int LF_KEY_F1 = 290;
constexpr int LF_KEY_F2 = 291;
constexpr int LF_KEY_F3 = 292;
constexpr int LF_KEY_F4 = 293;
constexpr int LF_KEY_F5 = 294;
constexpr int LF_KEY_F6 = 295;
constexpr int LF_KEY_F7 = 296;
constexpr int LF_KEY_F8 = 297;
constexpr int LF_KEY_F9 = 298;
constexpr int LF_KEY_F10 = 299;
constexpr int LF_KEY_F11 = 300;
constexpr int LF_KEY_F12 = 301;
constexpr int LF_KEY_F13 = 302;
constexpr int LF_KEY_F14 = 303;
constexpr int LF_KEY_F15 = 304;
constexpr int LF_KEY_F16 = 305;
constexpr int LF_KEY_F17 = 306;
constexpr int LF_KEY_F18 = 307;
constexpr int LF_KEY_F19 = 308;
constexpr int LF_KEY_F20 = 309;
constexpr int LF_KEY_F21 = 310;
constexpr int LF_KEY_F22 = 311;
constexpr int LF_KEY_F23 = 312;
constexpr int LF_KEY_F24 = 313;
constexpr int LF_KEY_F25 = 314;
constexpr int LF_KEY_KP_0 = 320;
constexpr int LF_KEY_KP_1 = 321;
constexpr int LF_KEY_KP_2 = 322;
constexpr int LF_KEY_KP_3 = 323;
constexpr int LF_KEY_KP_4 = 324;
constexpr int LF_KEY_KP_5 = 325;
constexpr int LF_KEY_KP_6 = 326;
constexpr int LF_KEY_KP_7 = 327;
constexpr int LF_KEY_KP_8 = 328;
constexpr int LF_KEY_KP_9 = 329;
constexpr int LF_KEY_KP_DECIMAL = 330;
constexpr int LF_KEY_KP_DIVIDE = 331;
constexpr int LF_KEY_KP_MULTIPLY = 332;
constexpr int LF_KEY_KP_SUBTRACT = 333;
constexpr int LF_KEY_KP_ADD = 334;
constexpr int LF_KEY_KP_ENTER = 335;
constexpr int LF_KEY_KP_EQUAL = 336;
constexpr int LF_KEY_LEFT_SHIFT = 340;
constexpr int LF_KEY_LEFT_CONTROL = 341;
constexpr int LF_KEY_LEFT_ALT = 342;
constexpr int LF_KEY_LEFT_SUPER = 343;
constexpr int LF_KEY_RIGHT_SHIFT = 344;
constexpr int LF_KEY_RIGHT_CONTROL = 345;
constexpr int LF_KEY_RIGHT_ALT = 346;
constexpr int LF_KEY_RIGHT_SUPER = 347;
constexpr int LF_KEY_MENU = 348;

